pull_request_rules:
  - name: automatic merge for Scala Steward pull requests
    conditions:
      - author=scala-steward[bot]
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
